### ISSUE TITLE
Screen cast

### ISSUE THREAD

**Issue by dotnethii** [BrennanConroy/StreamR#3]
Please include the program Screen And Audio Sharing in this resource

**Comment by BrennanConroy** [comment]
No idea what you mean.

This is mostly demoware and it's very unlikely that any major additions will be made.

**Comment by dotnethii** [comment]
Your application is very useful. Please ScreenCast and Audio and webcam also add clients.
Thank you for helping to advance science.

**Comment by dotnethii** [comment]
Your application is very useful. Please ScreenCast and Audio and webcam also add clients.
Thank you for helping to advance science.
